### ISSUE TITLE
Issue when purchasing a simple virtual product with configurable downloadable products

### ISSUE THREAD

**Issue by oliverh-cf** [crankycyclops/Crankycyclops_ConfigurableProduct#1]
Not sure if this project is dead or not, but I'm having an issue where there are no links being sent in the confirmation email when there are simple virtual products on the order. I have the following error in the exception log"
> [2021-08-23 14:21:56] main.CRITICAL: Notice: Undefined offset: 0 in [...]/app/code/Crankycyclops/ConfigurableProduct/Block/Sales/Order/Email/Items/ConfigurableProduct.php on line 83 {"exception":"[object] (Exception(code: 0): Notice: Undefined offset: 0 in [...]/app/code/Crankycyclops/ConfigurableProduct/Block/Sales/Order/Email/Items/ConfigurableProduct.php on line 83 at [...]/vendor/magento/framework/App/ErrorHandler.php:61)"} []

Currently running Magento 2.4.2. Let me know if you need more information!

**Comment by crankycyclops** [comment]
HI @oliverh-cf, yeah, the problem is probably at least in part due to the fact that I copied code from an old version of one of Magento's classes instead of extending it and making my changes properly. I'm not surprised it broke on 2.4. I haven't done any Magento work in a while. I might take a look at this, but I've been busy with other projects, so I can't guarantee it'll get fixed soon. If you'd like to tackle it and submit a PR, I'd be happy to merge the change.

**Comment by peterjaap** [comment]
@oliverh-cf running into this now, did you fix it by any chance?

**Comment by oliverh-cf** [comment]
I'm sorry to say we have not fixed this. As a stopgap we put a link to the customer account in the transaction email. So far our customers haven't had too much trouble downloading their purchase. Unfortunately because the stopgap has worked reasonable well so far, the priority for fixing this issue has dropped in the backlog.

**Comment by peterjaap** [comment]
Ok thanks! Unfortunately that's not an option for us since we also allow guest checkouts. I'll try to see if I can fix it :)

**Comment by peterjaap** [comment]
I did a PR here; https://github.com/crankycyclops/Crankycyclops_ConfigurableProduct/pull/2
